name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Install angular-cli-ghpages globally
      - name: Install angular-cli-ghpages
        run: npm install -g angular-cli-ghpages

      - name: Build
        run: npm run build -- --configuration production --base-href "https://aleandropresta.github.io/notes-app/"

      - name: Check build output
        run: ls -la dist/notes-app

      # Deploy using angular-cli-ghpages
      - name: Deploy to gh pages
        run: |
          npx angular-cli-ghpages --dir=dist/notes-app --no-silent

        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
